export const Constants = {
  CALENDAR: {
    UPDATE: 'UPDATE_CALENDAR',
    UPDATED: 'CALENDAR_UPDATED'
  },
  COUNTER: {
    UPDATE_ALL: 'UPDATE_COUNTERS',
    ALL_UPDATED: 'COUNTERS_UPDATED',
    UPDATE: 'UPDATE_COUNTER',
    UPDATED: 'COUNTER_UPDATED'
  },
  RESOURCE: {
    UPDATE: 'UPDATE_RESOURCES',
    UPDATED: 'RESOURCES_UPDATED',
    DRAGGED: 'DRAGGED',
    SELECTION_CHANGED: 'RESOURCE_SELECTION_CHANGED'
  },
  TASK: {
    UPDATE: 'UPDATE_TASKS',
    UPDATED: 'TASKS_UPDATED'
  },
  SCHEDULE: {
    UPDATE: 'UPDATE_SCHEDULE',
    UPDATED: 'SCHEDULE_UPDATED',
    NUMBER_CHANGE: 'NUMBER_CHANGE'
  },
  CONSTRAINTS: {
    TOGGLE_ABSENCE: 'TOGGLE_ABSENCE',
    UPDATED: 'CONSTRAINTS_UPDATED'
  },
  ASSIGNMENT: {
    ADD: 'ADD_ASSIGNMENT',
    UPDATE: 'UPDATE_ASSIGNMENTS',
    UPDATED: 'ASSIGNMENT_UPDATED',
    REMOVE: 'REMOVE_ASSIGNMENT'
  },
  ItemTypes: {
    RESOURCE: 'RESOURCE'
  }
}
